{% set name = "glass" %}
{% set version = "2025.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/glass-{{ version }}.tar.gz
  sha256: 7b1aa2394e16010f7f1b4243f49e7e12d7a4dd28fcbf3e3f7cf25ce4905a8615

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - cosmology >=2022.10.9
    - healpix >=2022.11.1
    - healpy >=1.15.0
    - numpy >=2.1.1
    - transformcl >=2022.8.9

test:
  imports:
    - glass
    - glass.algorithm
    - glass.arraytools
    - glass.fields
    - glass.galaxies
    - glass.grf
    - glass.lensing
    - glass.observations
    - glass.points
    - glass.shapes
    - glass.shells
    - glass.user
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://glass.readthedocs.io
  summary: Generator for Large Scale Structure
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ntessore
    - paddyroddy
    - Saransh-cpp
