schema_version: 1

context:
  name: glass
  version: "2025.2"
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/glass-${{ version }}.tar.gz
  sha256: f7b06bb3e8ca9dcd314e322a145873dc4df67811ec1f0015d74c5a933beb4c35

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - array-api-extra >=0.9.0
    - array-api-strict >=2.0
    - healpix >=2022.11.1
    - healpy >=1.15.0
    - transformcl >=2022.8.9
    - typing-extensions >=4.13.2

tests:
  - python:
      imports:
        - glass
        - glass.algorithm
        - glass.arraytools
        - glass.cosmology
        - glass.fields
        - glass.galaxies
        - glass.grf
        - glass.jax
        - glass.lensing
        - glass.observations
        - glass.points
        - glass.shapes
        - glass.shells
        - glass.user
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Generator for Large Scale Structure
  license: MIT
  license_file: LICENSE
  homepage: https://glass.readthedocs.io

extra:
  recipe-maintainers:
    - connoraird
    - ntessore
    - paddyroddy
    - Saransh-cpp
